/*
 * Run using the mongo shell. For remote databases, ensure that the
 * connection string is supplied in the command line. 
 * localhost:
 *   mongo music scripts/init.mongo.js
 */

db.like.remove({});  // Remove all entries in the likes collection

// Data to be inserted into the likes collection
const likesDB = [
    { 'track': 'Requiem: II. Dies irae', 'artist': 'Giuseppe Verdi', 'date': '2023-11-01' },
    { 'track': 'Gal a Bubble - Raw', 'artist': 'Konshens', 'date': '2023-11-02' },
    { 'track': 'Feed Me Diamonds - RAC Mix', 'artist': 'MNDR', 'date': '2023-11-03' },
    { 'track': 'El Sol No Regresa', 'artist': 'La Quinta Estacion', 'date': '2023-11-04' },
    { 'track': 'Let Me In', 'artist': 'Tarrus Riley', 'date': '2023-11-05' },
    { 'track': 'Piano Sonata No. 20 In A Major, D.959: 4. Rondo (Allegretto)', 'artist': 'Franz Schubert', 'date': '2023-11-06' },
    { 'track': "Split Feelin's - Remastered 1999/Rudy Van Gelder Edition", 'artist': 'Hank Mobley', 'date': '2023-11-07' },
    { 'track': 'Háblame de Ti', 'artist': 'Pecos', 'date': '2023-11-08' },
    { 'track': 'Ricercar No. 1 in G: Ricercar No. 1 in G', 'artist': 'Domenico Gabrielli', 'date': '2023-11-09' },
    { 'track': 'Holding On', 'artist': 'Disclosure', 'date': '2023-11-10' },
    { 'track': "Shadowboxin'", 'artist': 'GZA', 'date': '2023-11-11' },
    { 'track': 'Every Morning', 'artist': "Keb' Mo'", 'date': '2023-11-12' },
    { 'track': 'Come On In My Kitchen', 'artist': 'Robert Johnson', 'date': '2023-11-13' },
    { 'track': 'Serenade in E Major for Strings, Op. 22: II. Menuetto', 'artist': 'Antonín Dvořák', 'date': '2023-11-14' },
    { 'track': 'Prokofiev: Romeo and Juliet, Op. 64, Act 1, Scene 2: Dance of the Knights', 'artist': 'Sergei Prokofiev', 'date': '2023-11-15' },
    { 'track': 'Look At The Light', 'artist': 'Sin Fang', 'date': '2023-11-16' },
    { 'track': 'Jesus Christ', 'artist': 'Brand New', 'date': '2023-11-17' },
    { 'track': 'Naked As We Came', 'artist': 'Iron & Wine', 'date': '2023-11-18' },
    { 'track': 'Carbonated', 'artist': 'Mount Kimbie', 'date': '2023-11-19' },
    { 'track': 'Wild Horses - Live / Remastered 2009', 'artist': 'The Rolling Stones', 'date': '2023-11-20' },
    { 'track': 'Jesus Christ', 'artist': 'Brand New', 'date': '2023-11-21' },
    { 'track': 'Prokofiev: Romeo and Juliet, Op. 64, Act 1, Scene 2: Dance of the Knights', 'artist': 'Sergei Prokofiev', 'date': '2023-11-22' },
    { 'track': 'Cello Suite No. 1 in G Major, BWV 1007: I. Prélude', 'artist': 'Johann Sebastian Bach', 'date': '2023-11-23' },
    { 'track': 'Only Love', 'artist': 'Ben Howard', 'date': '2023-11-24' },
    { 'track': 'Lay Your Cards Out', 'artist': 'POLIÇA', 'date': '2023-11-25' },
    { 'track': 'Line of Fire', 'artist': 'Junip', 'date': '2023-11-26' },
    { 'track': 'I Feel It Coming', 'artist': 'The Weeknd', 'date': '2023-11-27' },
    { 'track': 'Line of Fire', 'artist': 'Junip', 'date': '2023-11-28' },
    { 'track': 'More Than Words', 'artist': 'Extreme', 'date': '2023-11-29' },
    { 'track': 'Look at Little Sister', 'artist': 'Stevie Ray Vaughan', 'date': '2023-11-30' },
    { 'track': 'Lingus', 'artist': 'Snarky Puppy', 'date': '2023-12-01' },
    { 'track': 'All the Wild Horses', 'artist': 'Ray LaMontagne', 'date': '2023-12-02' },
    { 'track': 'Hell Hound On My Trail', 'artist': 'Robert Johnson', 'date': '2023-12-03' },
    { 'track': "Rollin' Stone", 'artist': 'Muddy Waters', 'date': '2023-12-04' },
    { 'track': 'Girl On Fire', 'artist': 'Alicia Keys', 'date': '2023-12-05' },
    { 'track': 'Juke - Single Version', 'artist': 'Little Walter', 'date': '2023-12-06' },
    { 'track': 'Tzigane, M. 76 (Version for Violin & Orchestra)', 'artist': 'Maurice Ravel', 'date': '2023-12-07' },
    { 'track': 'Caroline', 'artist': 'Aminé', 'date': '2023-12-08' },
    { 'track': 'Carbonated', 'artist': 'Mount Kimbie', 'date': '2023-12-09' },
    { 'track': 'Ghosts', 'artist': 'Laura Marling', 'date': '2023-12-10' },
    { 'track': 'Drops of Jupiter (Tell Me)', 'artist': 'Train', 'date': '2023-12-11' },
    { 'track': 'Back Door Man', 'artist': "Howlin' Wolf", 'date': '2023-12-12' },
    { 'track': 'Pictures at an Exhibition (Orch. Ravel): Promenade 1 - Live', 'artist': 'Modest Mussorgsky', 'date': '2023-12-13' },
    { 'track': "Don't Owe You a Thang", 'artist': 'Gary Clark Jr.', 'date': '2023-12-14' },
    { 'track': 'For Emma', 'artist': 'Bon Iver', 'date': '2023-12-15' },
    { 'track': 'Voodoo Child (Slight Return) - Live', 'artist': 'Stevie Ray Vaughan', 'date': '2023-12-16' },
    { 'track': 'Caroline', 'artist': 'Aminé', 'date': '2023-12-17' },
    { 'track': "The Ecstasy of Gold - L'Estasi Dell'oro", 'artist': 'Ennio Morricone', 'date': '2023-12-18' },
    { 'track': 'Who Says', 'artist': 'John Mayer', 'date': '2023-12-19' },
    { 'track': 'Skinny Love', 'artist': 'Bon Iver', 'date': '2023-12-20' },
    { 'track': 'Carbonated', 'artist': 'Mount Kimbie', 'date': '2023-12-21' },
    { 'track': 'Naked As We Came', 'artist': 'Iron & Wine', 'date': '2023-12-22' },
    { 'track': 'In The Midnight', 'artist': 'Langhorne Slim', 'date': '2023-12-23' },
    { 'track': 'Scene Five - With Ears To See and Eyes To Hear', 'artist': 'Sleeping With Sirens', 'date': '2023-12-24' },
    { 'track': 'All Your Love - Mono', 'artist': 'John Mayall & The Bluesbreakers', 'date': '2023-12-25' },
    { 'track': 'Fit Against the Country', 'artist': 'Horse Feathers', 'date': '2023-12-26' },
    { 'track': 'Change It', 'artist': 'Stevie Ray Vaughan', 'date': '2023-12-27' },
    { 'track': 'Every Morning', 'artist': "Keb' Mo'", 'date': '2023-12-28' },
    { 'track': 'Naked As We Came', 'artist': 'Iron & Wine', 'date': '2023-12-29' },
    { 'track': "The Times They Are A-Changin'", 'artist': 'Bob Dylan', 'date': '2023-12-30' },
    { 'track': 'Every Morning', 'artist': "Keb' Mo'", 'date': '2023-12-31' },
    { 'track': 'Alone Again (Naturally)', 'artist': 'Diana Krall', 'date': '2024-01-01' },
    { 'track': 'Bewitched, Bothered, And Bewildered', 'artist': 'Ella Fitzgerald', 'date': '2024-01-02' },
    { 'track': 'New Slang', 'artist': 'The Shins', 'date': '2024-01-03' },
    { 'track': 'Another Brick in the Wall, Pt. 2', 'artist': 'Pink Floyd', 'date': '2024-01-04' },
    { 'track': 'New Slang', 'artist': 'The Shins', 'date': '2024-01-05' },
    { 'track': "Somebody's Sleeping in My Bed", 'artist': 'Buddy Guy', 'date': '2024-01-06' },
    { 'track': 'Flaming Creatures', 'artist': 'Hrvrd', 'date': '2024-01-07' },
    { 'track': 'Hurricane', 'artist': 'MS MR', 'date': '2024-01-08' },
    { 'track': 'Fit Against the Country', 'artist': 'Horse Feathers', 'date': '2024-01-09' },
    { 'track': 'Caroline', 'artist': 'Aminé', 'date': '2024-01-10' },
    { 'track': 'New Slang', 'artist': 'The Shins', 'date': '2024-01-11' },
    { 'track': 'Another Brick in the Wall, Pt. 2', 'artist': 'Pink Floyd', 'date': '2024-01-12' },
    { 'track': 'Song 2 - 2012 Remaster', 'artist': 'Blur', 'date': '2024-01-13' },
    { 'track': 'Naked As We Came', 'artist': 'Iron & Wine', 'date': '2024-01-14' },
    { 'track': "The Times They Are A-Changin'", 'artist': 'Bob Dylan', 'date': '2024-01-15' },
    { 'track': 'Fit Against the Country', 'artist': 'Horse Feathers', 'date': '2024-01-16' },
    { 'track': 'Naked As We Came', 'artist': 'Iron & Wine', 'date': '2024-01-17' },
    { 'track': "The Times They Are A-Changin'", 'artist': 'Bob Dylan', 'date': '2024-01-18' },
    { 'track': 'My Little Brown Book', 'artist': 'Duke Ellington', 'date': '2024-01-19' },
    { 'track': 'Goodbye Pork Pie Hat', 'artist': 'Charles Mingus', 'date': '2024-01-20' },
    { 'track': 'Dum Dum', 'artist': 'Baauer', 'date': '2024-01-21' },
    { 'track': 'Cool Kids', 'artist': 'Echosmith', 'date': '2024-01-22' },
    { 'track': 'Towers', 'artist': 'Bon Iver', 'date': '2024-01-23' },
    { 'track': "Somebody's Sleeping in My Bed", 'artist': 'Buddy Guy', 'date': '2024-01-24' },
    { 'track': 'Carbonated', 'artist': 'Mount Kimbie', 'date': '2024-01-25' },
    { 'track': 'Ghosts', 'artist': 'Laura Marling', 'date': '2024-01-26' },
    { 'track': 'Carbonated', 'artist': 'Mount Kimbie', 'date': '2024-01-27' },
    { 'track': 'Ghosts', 'artist': 'Laura Marling', 'date': '2024-01-28' },
    { 'track': 'Naked As We Came', 'artist': 'Iron & Wine', 'date': '2024-01-29' },
    { 'track': 'Caroline', 'artist': 'Aminé', 'date': '2024-01-30' },
    { 'track': 'Another Brick in the Wall, Pt. 2', 'artist': 'Pink Floyd', 'date': '2024-01-31' },
    { 'track': 'New Slang', 'artist': 'The Shins', 'date': '2024-02-01' },
    { 'track': 'New Slang', 'artist': 'The Shins', 'date': '2024-02-02' },
    { 'track': 'Carbonated', 'artist': 'Mount Kimbie', 'date': '2024-02-03' },
    { 'track': 'Black and Yellow', 'artist': 'Wiz Khalifa', 'date': '2024-02-04' },
    { 'track': 'Ghosts', 'artist': 'Laura Marling', 'date': '2024-02-05' },
    { 'track': 'The Girl', 'artist': 'City and Colour', 'date': '2024-02-06' },
    { 'track': 'Naked As We Came', 'artist': 'Iron & Wine', 'date': '2024-02-07' },
    { 'track': 'Hat And Beard', 'artist': 'Eric Dolphy', 'date': '2024-02-08' },
    { 'track': 'Fit Against the Country', 'artist': 'Horse Feathers', 'date': '2024-02-09' },
    { 'track': 'Another Brick in the Wall, Pt. 2', 'artist': 'Pink Floyd', 'date': '2024-02-10' },
    { 'track': 'New Slang', 'artist': 'The Shins', 'date': '2024-02-11' },
    { 'track': 'Caroline', 'artist': 'Aminé', 'date': '2024-02-12' },
    { 'track': 'New Slang', 'artist': 'The Shins', 'date': '2024-02-13' },
    { 'track': "The Times They Are A-Changin'", 'artist': 'Bob Dylan', 'date': '2024-02-14' },
    { 'track': 'Fit Against the Country', 'artist': 'Horse Feathers', 'date': '2024-02-15' },
    { 'track': 'Naked As We Came', 'artist': 'Iron & Wine', 'date': '2024-02-16' },
    { 'track': 'Ghosts', 'artist': 'Laura Marling', 'date': '2024-02-17' },
    { 'track': "The Times They Are A-Changin'", 'artist': 'Bob Dylan', 'date': '2024-02-18' },
    { 'track': 'Another Brick in the Wall, Pt. 2', 'artist': 'Pink Floyd', 'date': '2024-02-19' },
    { 'track': 'You Got Me', 'artist': 'G-Eazy', 'date': '2024-02-20' },
    { 'track': 'Omen - Radio Edit', 'artist': 'Disclosure', 'date': '2024-02-21' },
    { 'track': 'Fit Against the Country', 'artist': 'Horse Feathers', 'date': '2024-02-22' },
    { 'track': 'Carbonated', 'artist': 'Mount Kimbie', 'date': '2024-02-23' },
    { 'track': 'Caroline', 'artist': 'Aminé', 'date': '2024-02-24' },
    { 'track': 'Caroline', 'artist': 'Aminé', 'date': '2024-02-25' },
    { 'track': 'Caroline', 'artist': 'Aminé', 'date': '2024-02-26' },
    { 'track': 'Ghosts', 'artist': 'Laura Marling', 'date': '2024-02-27' },
    { 'track': 'Ghosts', 'artist': 'Laura Marling', 'date': '2024-02-28' },
    { 'track': 'Ghosts', 'artist': 'Laura Marling', 'date': '2024-02-29' },
    { 'track': 'Requiem: II. Dies irae', 'artist': 'Giuseppe Verdi', 'date': '2024-03-01' },
    { 'track': 'Gal a Bubble - Raw', 'artist': 'Konshens', 'date': '2024-03-02' },
    { 'track': 'Feed Me Diamonds - RAC Mix', 'artist': 'MNDR', 'date': '2024-03-03' },
    { 'track': 'El Sol No Regresa', 'artist': 'La Quinta Estacion', 'date': '2024-03-04' },
    { 'track': 'Let Me In', 'artist': 'Tarrus Riley', 'date': '2024-03-05' },
    { 'track': 'Piano Sonata No. 20 In A Major, D.959: 4. Rondo (Allegretto)', 'artist': 'Franz Schubert', 'date': '2024-03-06' },
    { 'track': "Split Feelin's - Remastered 1999/Rudy Van Gelder Edition", 'artist': 'Hank Mobley', 'date': '2024-03-07' },
    { 'track': 'Háblame de Ti', 'artist': 'Pecos', 'date': '2024-03-08' },
    { 'track': 'Ricercar No. 1 in G: Ricercar No. 1 in G', 'artist': 'Domenico Gabrielli', 'date': '2024-03-09' },
    { 'track': 'Holding On', 'artist': 'Disclosure', 'date': '2024-03-10' },
    { 'track': "Shadowboxin'", 'artist': 'GZA', 'date': '2024-03-11' },
    { 'track': 'Every Morning', 'artist': "Keb' Mo'", 'date': '2024-03-12' },
    { 'track': 'Come On In My Kitchen', 'artist': 'Robert Johnson', 'date': '2024-03-13' },
    { 'track': 'Serenade in E Major for Strings, Op. 22: II. Menuetto', 'artist': 'Antonín Dvořák', 'date': '2024-03-14' },
    { 'track': 'Prokofiev: Romeo and Juliet, Op. 64, Act 1, Scene 2: Dance of the Knights', 'artist': 'Sergei Prokofiev', 'date': '2024-03-15' },
    { 'track': 'Look At The Light', 'artist': 'Sin Fang', 'date': '2024-03-16' },
    { 'track': 'Jesus Christ', 'artist': 'Brand New', 'date': '2024-03-17' },
    { 'track': 'Naked As We Came', 'artist': 'Iron & Wine', 'date': '2024-03-18' },
    { 'track': 'Carbonated', 'artist': 'Mount Kimbie', 'date': '2024-03-19' },
    { 'track': 'Wild Horses - Live / Remastered 2009', 'artist': 'The Rolling Stones', 'date': '2024-03-20' },
    { 'track': 'Jesus Christ', 'artist': 'Brand New', 'date': '2024-03-21' },
    { 'track': 'Prokofiev: Romeo and Juliet, Op. 64, Act 1, Scene 2: Dance of the Knights', 'artist': 'Sergei Prokofiev', 'date': '2024-03-22' },
    { 'track': 'Cello Suite No. 1 in G Major, BWV 1007: I. Prélude', 'artist': 'Johann Sebastian Bach', 'date': '2024-03-23' },
    { 'track': 'Only Love', 'artist': 'Ben Howard', 'date': '2024-03-24' },
    { 'track': 'Lay Your Cards Out', 'artist': 'POLIÇA', 'date': '2024-03-25' },
    { 'track': 'Line of Fire', 'artist': 'Junip', 'date': '2024-03-26' },
    { 'track': 'I Feel It Coming', 'artist': 'The Weeknd', 'date': '2024-03-27' },
    { 'track': 'Line of Fire', 'artist': 'Junip', 'date': '2024-03-28' },
    { 'track': 'More Than Words', 'artist': 'Extreme', 'date': '2024-03-29' },
    { 'track': 'Look at Little Sister', 'artist': 'Stevie Ray Vaughan', 'date': '2024-03-30' },
    { 'track': 'Lingus', 'artist': 'Snarky Puppy', 'date': '2024-03-31' },
    { 'track': 'All the Wild Horses', 'artist': 'Ray LaMontagne', 'date': '2024-04-01' },
    { 'track': 'Hell Hound On My Trail', 'artist': 'Robert Johnson', 'date': '2024-04-02' },
    { 'track': "Rollin' Stone", 'artist': 'Muddy Waters', 'date': '2024-04-03' },
    { 'track': 'Girl On Fire', 'artist': 'Alicia Keys', 'date': '2024-04-04' },
    { 'track': 'Juke - Single Version', 'artist': 'Little Walter', 'date': '2024-04-05' },
    { 'track': 'Tzigane, M. 76 (Version for Violin & Orchestra)', 'artist': 'Maurice Ravel', 'date': '2024-04-06' },
    { 'track': 'Caroline', 'artist': 'Aminé', 'date': '2024-04-07' },
    { 'track': 'Carbonated', 'artist': 'Mount Kimbie', 'date': '2024-04-08' },
    { 'track': 'Ghosts', 'artist': 'Laura Marling', 'date': '2024-04-09' },
    { 'track': 'Drops of Jupiter (Tell Me)', 'artist': 'Train', 'date': '2024-04-10' },
    { 'track': 'Back Door Man', 'artist': "Howlin' Wolf", 'date': '2024-04-11' },
    { 'track': 'Pictures at an Exhibition (Orch. Ravel): Promenade 1 - Live', 'artist': 'Modest Mussorgsky', 'date': '2024-04-12' },
    { 'track': "Don't Owe You a Thang", 'artist': 'Gary Clark Jr.', 'date': '2024-04-13' },
    { 'track': 'For Emma', 'artist': 'Bon Iver', 'date': '2024-04-14' },
    { 'track': 'Voodoo Child (Slight Return) - Live', 'artist': 'Stevie Ray Vaughan', 'date': '2024-04-15' }
];

db.like.insertMany(likesDB); // Insert the data into the likes collection
const count = db.like.count(); // Count the number of documents inserted
print('Inserted', count, 'like');

db.counters.remove({ _id: 'like' }); // Remove existing counters for likes
db.counters.insert({ _id: 'like', current: count }); // Create a new counter

// Create indexes to improve query performance
db.like.createIndex({ date: 1 }); // Create an index on the date field
db.like.createIndex({ track: 1, artist: 1, date: 1 }, { unique: true }); // Create a compound index

